version: 2
updates:

  - package-ecosystem: gomod
    commit-message:
      prefix: chore
    directory: /
    schedule:
      interval: monthly
    groups:
      golang-dependencies:
        patterns:
          - "*"
    reviewers:
      - "mendersoftware/client-dependabot-reviewers"
